modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
[[mods]]
modId="progexpansion" #mandatory
version="1.16.1-1.0.0" #mandatory
displayName="Progression Expansion" #mandatory
authors="Nylanomel, Pylerrr" #optional
description='''A mod to increase and expand the progression of minecraft with a single mod'''
[[dependencies.progexpansion]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.progexpansion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2, )"
    ordering="NONE"
    side="BOTH"
