modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="progexpansion"
version="1.16.1-0.3.0"
displayName="Progression Expansion"
authors="Nylanomel, Pylerrr"
description='''
A mod to increase and expand the progression of minecraft with a single mod
'''
[[dependencies.progexpansion]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.progexpansion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
